# Generated by Django 3.0.8 on 2020-08-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='dishes',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
