# Generated by Django 3.0.8 on 2020-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restname/'),
        ),
    ]
