# Generated by Django 3.0.8 on 2020-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200805_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='addres',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rest',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rest',
            name='discription',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='rest',
            name='image',
            field=models.ImageField(default=1, upload_to='restname/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rest',
            name='name_res',
            field=models.CharField(max_length=20),
        ),
    ]
