# Generated by Django 3.0.8 on 2020-08-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200805_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='food/')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Rest')),
            ],
        ),
    ]
